# Objetivos

* **MÓDULOS PERDIDOS**: Reportar sobre los datasets ligados a un diagnóstico específico cuya composición es 100% nulo, es decir, que no se realizaron o perdieron todos sus datos por algún error humano o de sistema.
* **DATASETS DE COMPOSICIÓN**: Documentar el significado de las columnas dentro de los archivos de composiciones de preguntas dentro de la carpeta *Python/resultados/composiciones*.
* **REPORTE DE PREGUNTAS BASALES**: Reportar las preguntas basales encontradas y las razones para su determinación.

In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from plotly.subplots import make_subplots
from pathlib import Path

import utils as ut

In [3]:
df_sintomas_disc = pd.read_excel(r"C:\Users\Lan_1\Documents\VictorL_TesinaMACI\VictorL_TesinaMACI\Python\data\Sintomas_disc_Infante_Juvenil_n=1558.xlsx")

In [4]:
full_dict = ut.build_full_dict(df_sintomas_disc)

# MÓDULOS PERDIDOS

Ahora se presentan los módulos cuya composición es 100% nula.

In [6]:
rows = []

for code, info in full_dict.items():
    full_nan = (info['df_comp_full']['pct_nan'] == 100).all()
    rows.append({
        "code": code,
        "Nombre": info["nombre"],
        "Módulo": info["modulo"],
        "Perdido": full_nan
    })

df_result = pd.DataFrame(rows)
display(df_result)

   code                                             Nombre Módulo  Perdido
0   pag                                         Agorafobia      A     True
1   psp                                   Fobia específica      A     True
2   pso                                       Fobia social      A    False
3   pga                              Ansiedad generalizada      A    False
4   psm                                  Mutismo selectivo      A     True
5   ppa                                             Pánico      A     True
6   ppt                 Trastorno por estrés postraumático      A     True
7   psa                            Ansiedad por separación      A    False
8   poc                      Trastorno obsesivo-compulsivo      A     True
9   pea                                            Bulimia      B    False
10  pel                           Trastorno de eliminación      B     True
11  ppi                                               Pica      B     True
12  ptc                                  Trastorno de tics      B     True
13  ptr                                     Tricotilomanía      B     True
14  pmd                         Depresión mayor o distimia      C    False
15  pma                                  Manía o hipomanía      C    False
16  psz                                      Esquizofrenia      D    False
17  pad  Trastorno por déficit de atención e hiperactiv...      E    False
18  pcd                              Trastorno de conducta      E    False
19  pod                  Trastorno de oposición desafiante      E    False
20  pal                                   Abuso de alcohol      F    False
21  pmj                               Consumo de marihuana      F    False
22  psu                        Consumo de otras sustancias      F    False
23  pni                                  Consumo de tabaco      F    False

# DATASETS DE COMPOSICIÓN

Los siguientes datasets de composición, guardados en .csv y .xlsx dentro de la carpeta Python/resultados/composiciones cuentan con las siguientes columnas:

| Nombre de Columna | Descripción |
|-----------|-----------|
|      question     |  Código de la pregunta con la forma estándar *(cod)(dig)(abc)*, donde *(cod)* es el código correspondiente a cada diagnóstico, *(dig)* son 3 dígitos ordinales y *(abc)* son caracteres opcionales que indican preguntas de seguimiento.        |
|     cnt_non_nan      |    Conteo total de respuestas no perdidas de un total de N=1558       |
|     pct_non_nan      |    Prcentaje total de respuestas no perdidas de un total de N=1558       |
|cnt_non_standard|Conteo total de respuestas distintas al conjunto {2, 0, 3, 7, 77, 8, 88, 9, 99 o NaN} de un total de N=1558|
|pct_non_standard|Porcentaje total de respuestas distintas al conjunto conjunto {2, 0, 3, 7, 77, 8, 88, 9, 99 o NaN} de un total de N=1558|
|cnt_*| Conteo único para la respuesta *, incluyendo al conjunto {2, 0, 3, 7, 77, 8, 88, 9, 99 o NaN}. Para el subconjunto {2, 0, 3, 7, 77, 8, 88, 9 y 99} se agrega una aclaración sobre el significado de la respuesta estándar, ver abajo. |
|cnt_*| Porcentaje para la respuesta * de un total de N=1558, incluyendo al conjunto {2, 0, 3, 7, 77, 8, 88, 9, 99 o NaN}. Para el subconjunto {2, 0, 3, 7, 77, 8, 88, 9 y 99} se agrega una aclaración sobre el significado de la respuesta estándar, ver abajo. |

Respuestas estándar:

|Numéricamente| Significado| Código|
|---|---|---|
|2|Sí|_SI|
|0|No|_NO|
|3| A veces / De alguna manera| _AV/A|
|7, 77| Se niega a respoder| _NR|
|8, 88| No aplica| _NA|
|9, 99| No sabe| _NS|

In [8]:
save_done=False

if save_done == True:
    out_dir = Path.cwd() / "resultados" / "composiciones" / "csv"
    out_dir.mkdir(parents=True, exist_ok=True)
    
    for code, info in full_dict.items():
        info["df_comp_full"].to_csv(out_dir / f"{code}_comp.csv", index=False)

In [9]:
if save_done == True:
    out_dir = Path.cwd() / "resultados" / "composiciones" / "xlsx"
    out_dir.mkdir(parents=True, exist_ok=True)
    
    for code, info in full_dict.items():
        info["df_comp_full"].to_excel(out_dir / f"{code}_comp.xlsx", index=False)

# REPORTE DE PREGUNTAS BASALES

La metodología para encontrar las preguntas basales sin revisar el contenido de ninguna de ellas es sencillo: De forma efectiva, sólo se ordenan en razón de sus nulos, se asume una "tolerancia" y se encuentran umbrales de corte, donde la nulidad se dispara. En este sentido la tolerancia refleja el porcentaje máximo (excluyente) asumido de preguntas basales para un conjunto de preguntas desconocidas; y los umbrales son el máximo porcentaje de valores nulos dentro de una pregunta para ser considerada basal. A menor tolerancia, se obtienen menores umbrales.

A continuación, para cada módulo, se reportan las preguntas con menores nulos, según esta metodología. Además, al hacer la revisión dentro de cada módulo, se comprobaron los "cortes", es decir aquellos quiebres en la continuidad numérica de las pregutas. Si se reportan como basales las preguntas 1, 2, 4 y 5, dentro de un conjunto donde se tienen preguntas de la 1 a la 10, sería necesario evaluar si luego de la pregunta 2 se da alguna indicación dentro del cuestionario que permita saltar la pregunta 3 y, luego de la 5, saltar al siguiente módulo. De esta forma se encontraría el mínimo número de preguntas que deben ser respondidas.

Éste análisis es claramente perfectible y podría requerir de análisis experto.

En el anexo es posible encontrar las preguntas para las primeras 3 menores tolerancias.

## Fobia Social - pso

**Basales: 1-5**

Luego de la pregunta 5 se da la siguiente indicación: 


>a:	SI SE CODIFICO ALGUNA RESPUESTA CON * EN LAS P 3 - 5, CONTINUE
>
>		CUALQUIER OTRA RESPUESTA, PASE A TASEP, PAG.  9

Es decir, que el output es correcto sólo pso001-5 son basales

---

## Ansiedad generalizada - pga

**Basales: 1-5, 23-29**

En este caso hay una anomalía, ya que hay más datos perdidos en pga001 que en pga002-5 y pga023-29. aún así, estos resultados tienen sentido, luego de 5 se da la instrucción:

>h:	SI SE CODIFICARON 1 O MAS RESPUESTAS CON * EN LAS P 1-5, CONTINUE
>
>		CUALQUIER OTRA RESPUESTA, PASE A LA P23 , PAG. 56

Y  luego de la 29:

>m:	SI SE CODIFICO UNA RESPUESTA CON π EN LA P6, CONTINUE
>
>		CUALQUIER OTRA RESPUESTA, PASE A MUSE, PAG. 59

---

## Ansiedad por separación - psa

**Basales: 1-12**

Luego de la pregunta 1 se indica:

>	a:	SI EL NIÑO NO ASISTIO A LA ESCUELA NI AL TRABAJO EN EL ULTIMO AÑO, CODIFIQUE "8" EN LA P 2 Y PASE A LA P 3.

Lo que indica que algunos datos que debían codificarse como *8* se codificaron como NaN, o que, genuinamente, se perdieron por el sistema. Además, luego de la pregunta 12, se indica:

> d:	SI SE CODIFICARON 2 O MAS RESPUESTAS CON [ ] EN LAS P 1 - 12 Y EN LAS NOTAS 1 -  4, CONTINUE
>
>	CUALQUIER OTRA RESPUESTA, PASE A FOESP EN LA PAG. 19

---

## Bulimia - pea

**Basales: 1-4, 10-12, 20**

Es importante notar de los códigos que, dado que se pide medidas en distintos sistemas, la letra tras el número refleja la medida utilizada, por ejemplo, en la pregunta 2 se tiene *pea002k* y *pea002l*, que representan pesos en kilos y libras, respectivamente, pero ambas apuntan a la pregunta 2.

Parece haber una mayor cantidad de datos no codificados en la pregunta 1 que en el resto de preguntas basales.

Luego, en cuanto a la continuidad, tras la pregunta 4 se indica:

>NOTA 4:	¿SE CODIFICO ALGUNA RESPUESTA CON * EN LA NOTA 3 O LA P 4? 
>
>SI DICE SI:	CONTINUE
>SI DICE NO:	PASE A LA P10

Luego de la pregunta 12

>b.	SI SE CODIFICO ALGUNA RESPUESTA CON { } EN LA NOTA 4 O UNA RESPUESTA CON π EN P 12D, CONTINUE
>
>CUALQUIER OTRA RESPUESTA, PASE AL RECUADRO DE INSTRUCCIONES “d”, PAG. 9

El cuadro d indica:

>d: 	SI ES VARON, CODIFIQUE “8" EN LA P 20 Y PASE AL RECUADRO DE INSTRUCCIONES “e”, PAG. 11
>
>		CUALQUIER OTRA RESPUESTA, CONTINUE

Luego de la pregunta 20:

>  e:	SI SE CODIFICO { } EN LA NOTA 4 Y SE CODIFICARON UNA O MAS RESPUESTAS CON <> EN LA P 10-18 (Vea hoja de registro), PASE A P 21
>
>	CUALQUIER OTRA RESPUESTA, PASE AL RECUADRO DE INSTRUCCIONES “f”

Luego:

>f:	SI SE CODIFICARON 2 O MAS RESPUESTAS CON [ ] EN LAS  P10-19 Y LA NOTA 5, PASE A P22.
>
>		CUALQUIER OTRA RESPUESTA, PASE A ELIM, PAG 17

---


## Depresión mayor o distimia - pmd

**Basales: 1-22, 35**

Luego de la pregunta 22 se indica:

>NOTA 10:	¿SE CODIFICARON TRES O MAS RESPUESTAS CON [ ] EN LA P2 Y EN LAS NOTAS 2-9?
>
>SI DICE SI:	CONTINUE
>SI DICE NO:	PASE A LA P35, PAG. 21

Luego, en la pregunta 35 se da un condicional dentro de sus preguntas contingentes:

>   f:	SI SE CODIFICO ALGUNA RESPUESTA CON *  EN LA P 35B, PASE A LA P 37
>
>	CUALQUIER OTRA RESPUESTA, CONTINUE

Pero la pregunta 37 no es basal porque en la pregunta 36 se indica:

>   g:	SI SE CODIFICO ALGUNA RESPUESTA CON * EN LA P36B, CONTINUE
>
>CUALQUIER OTRA RESPUESTA, PASE A MAN/HIPOMAN, PAG. 29

---

## Manía o hipomanía - pma

**Basales: 1-13**

En la pregunta, 13, previo a contestar la pregunta 14 se indica:

>  o:	SI NO SE CODIFICO ALGUNA RESPUESTA CON * EN LAS P 1-2, PASE A LA NOTA 1
>
>CUALQUIER OTRA RESPUESTA, CONTINUE

Mientras que la nota 1 indica:

>  NOTA 1:	¿SE CODIFICARON 2 O MAS RESPUESTAS CON [ ] EN LAS P 3 - 14?
>
>SI DICE SI:		CONTINUE
>SI DICE NO:	PASE AL MODULO D

---

## Esquizofrenia - psz

**Basales: 1-2, 9-14**

Luego de la pregunta 2, si se contesta "No", se indica:

>  a:	SI SE CODIFICO ALGUNA RESPUESTA CON [ ] EN LAS NOTAS 1 - 3 Y P 3, CONTINUE
>
>		CUALQUIER OTRA RESPUESTA, PASE A LA P 9, PAG. 6

Y luego de la 14:

> NOTA 17:		ESTE ES UN PATRON DE SALTO OPCIONAL
>
>ENTREVISTADOR:	¿SE CODIFICO ALGUNA RESPUESTA CON π EN LAS P 1 - 14 O EN LA NOTA 4?
>
>SI DICE SI:		CONTINUE
>SI DICE NO:	PASE AL PROXIMO   MODULO
>(SI PROCEDE EN EL SONDEO DE ESQUIZOFRENIA)

---

## Trastorno por déficit de atención e hiperactividad - pad

**Basales: 1-2, 4-11, 22-25, 27-29, 31-33, 44**

Luego de la pregunta 2d, si se contesta "Sí", se pasa a la Nota 1, posterior a la pregunta 3, luego, al llegar a la pregunta 11 se indica:

>	a.	SI SE CODIFICARON 3 O MAS RESPUESTAS CON [  ] EN LAS    P 1-10 Y LA NOTA 1 (hoja de registro), CONTINUE
>
>		CUALQUIER OTRA RESPUESTA, PASE A LA P 22, PAG. 10	

Luego de la pregunta 25d, si se contesta "Sí", se pasa a la Nota 2, posterior a la pregunta 26 y lo mismo pasa para la preguntas 29d, Nota 3 y pregunta 30, respectivamente. En la pregunta 33d al ser respondida con con "No", se pasa al cuadro de instrucciones g:

>g:	SI SE CODIFICARON 3 O MAS RESPUESTAS CON [ ] EN LAS P 22 - 32 Y EN LAS NOTAS DE LA 2 - 3 (vea hoja de registro), CONTINUE
>
>CUALQUIER OTRA RESPUESTA, PASE A LA P 44, PAG. 18

Luego de la pregunta 44, se indica:
								
>	m:	SI SE CODIFICARON 4 O MAS RESPUESTAS CON [ ] EN LAS P 1-32 Y EN LAS NOTAS DE LA 1 - 3 O ALGUNA RESPUESTA CON † EN LA P 44 ) (vea hoja de registro), CONTINUE
>
>		CUALQUIER OTRA RESPUESTA, PASE A TOD, PAG. 21

---
                                
## Trastorno de conducta - pcd

**Basales: 1-4, 7-9, 12-15, 19-23, 25, 27-29, 39**

Las preguntas 5 y 6 sólo se responden si hay respuestas con * en las preguntas 1-4. Lo mismo ocurre con las preguntas 10-11 dependiendo de las respuestas de 7-9 y con las preguntas 16-17, dependiendo de las respuestas de 14-15. En el caso de la pregunta 18, ocurre lo siguiente:

>a:	SI EL NIÑO NUNCA ASISTIO A LA ESCUELA NI TRABAJO, CODIFIQUE “8" EN LA P 18, LUEGO PASE A LA P 19

Con lo quue es probable que los valores que debieron ser *8* se codificaron como NaN. En la pregunta 24 se indica:

> 
PREGUNTA OPCIONAL	
>
>SOLO HAGA LA PREGUNTA DE ESTE RECUADRO SI HA SIDO APROBADA PARA SU ESTUDIO Y PARA LA EDAD DEL NIÑO.
>
>SI NO SE HACE ESTA PREGUNTA, CODIFIQUE "8" EN LA P24, Y LUEGO PASE A LA P25	
	
Con lo que la preunta 24 no se considera Basal. La pregunta 26 es contigente pues luego de la 25 se indica:

>  d:	SI SE CODIFICO ALGUNA RESPUESTA CON * Y CON † EN LA P 25, PASE A LA P 27
>
>	CUALQUIER OTRA RESPUESTA, CONTINUE

Luego de la pregunta 29, se indica:

>  f:	SI SE CODIFICARON 2 ó MAS RESPUESTAS CON [ ] EN LAS P 1-29 Y LAS NOTAS DE LA 1-5 (vea hoja de registro) CONTINUE
>
>		CUALQUIER OTRA RESPUESTA, PASE AL RECUADRO DE INSTRUCCIONES “h”, PAG. 61

El recuadro de instrucciones h indica:

>h:	SI EL NIÑO NUNCA ASISTIO A LA ESCUELA, CODIFIQUE “8" EN LAS P 36, P 37 Y P 38, LUEGO PASE A LA P 39

Luego de la 39, se indica:

>SI DICE NO, PASE AL RECUADRO DE INSTRUCCIONES “p”, PAG.58
		
Éste dice:	
	
>	p:	SI EL NIÑO NUNCA TRABAJO, CODIFIQUE “8" EN LA P 40, LUEGO PASE AL RECUADRO DE INSTRUCCIONES “q”
	
Luego:

>q:	SI SE CODIFICARON 2 O MAS RESPUESTAS CON [ ] EN LAS P 1 - 29 Y EN LAS NOTAS 1 - 5 (ver hoja de registro), CONTINUE
>
>	CUALQUIER OTRA RESPUESTA, PASE AL RECUADRO DE INSTRUCCIONES  “r”	

Luego:

>r:	SI SE CODIFICARON 3 O MAS RESPUESTAS CON [ ] EN LAS  
>P1-29 Y EN LAS NOTAS 1-5 (vea hoja de registro), PASE AL   MODULO F
>
>SI SE CODIFICARON 3 O MAS RESPUESTAS CON ‹ ›, CONTINUE
>     
>CUALQUIER OTRA RESPUESTA, PASE AL MODULO F

---

## Trastorno de oposición desafiante - pod

**Basales: 1-12**

Luego de la pregunta 12 se indica:

>g:		SI SE CODIFICARON 2 O MAS RESPUESTAS CON [ ] EN LAS P1-11 Y EN LAS NOTAS 1-3, CONTINUE
>
>					CUALQUIER OTRA RESPUESTA, PASE A TCD, PAG. 41

---

## Abuso de alcohol - pal

**Basal: 1**

Naturalmente, la única pregunta basal es la primera, ya que si no se ha probado, no es necesario seguir preguntando.

>SI DICE NO, PASE A TAB, PAG. 13

## Consumo de marihuana - pmj

**Basal: 1**

Mismo caso que con el alcohol.

>SI DICE NO, PASE A OTRAS SUBST., PAG. 37

---

## Consumo de otras sustancias - psu

**Basales: 1-11**

Luego de la pregunta 11, se indica:

>l:	SI HAY ALGUNA RESPUESTA CON “π” EN LAS P 1-11, CONTINUE
>
>		CUALQUIER OTRA RESPUESTA, PASE A LA NOTA 5, PAG. 61

Luego:

> 
>NOTA 5: 	SE CODIFICO ALGUNA RESPUESTA CON π O † EN P1-11?
>
>SI DICE SI:	CONTINUE
>SI DICE NO:	PASE AL MODULO TODA LA VIDA	

---

## Consumo de tabaco - pni

**Basales: 1-2**

Luego de la pregunta 2:

>SI DICE NO, PASE AL RECUADRO DE INSTRUCCIONES "c"

Luego:

>c.	SI SE CODIFICO  CON * LA RESPUESTA EN LA P  1B O LA P 2B, CONTINUE
>
>		CUALQUIER OTRA RESPUESTA, PASE A LA NOTA 3, PAG. 21 

Finalmente:

>NOTA 3:	¿SE CODIFICO ALGUNA  RESPUESTA CON  † EN LA P1 ó LA 2?
>
>SI DICE SI:	CONTINUE
>SI DICE NO:	PASE A MARIH PAG. 25

---

# Anexo

In [11]:
ut.tol_report(full_dict, 3)

Agorafobia - pag - N=64


------------------------------------------------------------------------------------------------------------------------------------------------------


Fobia específica - psp - N=70


------------------------------------------------------------------------------------------------------------------------------------------------------


Fobia social - pso - N=55
Tolerancia de 10% => Umbral de 0.06 a 43.97

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
0,pso001,0.064185,4.043646,95.892169,0.0,0.0,0.0,0.000000,0.0,0.0,True
2,pso002,0.064185,24.326059,75.609756,0.0,0.0,0.0,0.000000,0.0,0.0,True
3,pso003,0.064185,67.907574,32.028241,0.0,0.0,0.0,0.000000,0.0,0.0,True
5,pso004,0.064185,78.818999,20.924262,0.0,0.0,0.0,0.192555,0.0,0.0,True
6,pso005,0.064185,51.155327,48.652118,0.0,0.0,0.0,0.128370,0.0,0.0,True

Tolerancia de 13% => Umbral de 0.06 a 54.17

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
7,pso006,43.966624,12.451861,43.388960,0.0,0.0,0.0,0.192555,0.0,0.0,True
8,pso007,43.966624,37.355584,18.549422,0.0,0.0,0.0,0.128370,0.0,0.0,True

Tolerancia de 24% => Umbral de 54.17 a 67.01

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
9,pso008,54.172015,27.535302,18.292683,0.0,0.0,0.0,0.000000,0.0,0.0,True
10,pso009,54.172015,25.802311,20.025674,0.0,0.0,0.0,0.000000,0.0,0.0,True
11,pso010,54.172015,16.174583,29.589217,0.0,0.0,0.0,0.064185,0.0,0.0,True
12,pso011,54.172015,27.599487,18.164313,0.0,0.0,0.0,0.064185,0.0,0.0,True
13,pso012,54.172015,29.075738,16.688062,0.0,0.0,0.0,0.064185,0.0,0.0,True
14,pso013,54.172015,24.646983,21.181001,0.0,0.0,0.0,0.000000,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Ansiedad generalizada - pga - N=103
Tolerancia de 11% => Umbral de 0.13 a 2.89

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,limited
5,pga002,0.12837,82.284981,17.394095,0.0,0.0,0.0,0.192555,True
10,pga003,0.12837,61.489089,38.189987,0.0,0.0,0.0,0.192555,True
15,pga004,0.12837,49.101412,50.577664,0.0,0.0,0.0,0.192555,True
20,pga005,0.12837,76.315789,23.363286,0.0,0.0,0.0,0.192555,True
72,pga023,0.12837,71.887035,27.920411,0.0,0.0,0.0,0.064185,True
76,pga024,0.12837,60.397946,39.345315,0.0,0.0,0.0,0.128370,True
79,pga025,0.12837,71.758665,27.984596,0.0,0.0,0.0,0.128370,True
82,pga026,0.12837,71.437741,28.241335,0.0,0.0,0.0,0.192555,True
85,pga027,0.12837,77.920411,21.822850,0.0,0.0,0.0,0.128370,True
90,pga028,0.12837,81.899872,17.843389,0.0,0.0,0.0,0.128370,True
95,pga029,0.12837,84.980745,14.826701,0.0,0.0,0.0,0.064185,True

Tolerancia de 12% => Umbral de 0.13 a 42.68

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,limited
0,pga001,2.888318,53.530167,43.324775,0.0,0.0,0.064185,0.192555,True

Tolerancia de 13% => Umbral de 0.13 a 49.42

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,limited
25,pga006,42.682927,32.156611,25.160462,0.0,0.0,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Mutismo selectivo - psm - N=42


------------------------------------------------------------------------------------------------------------------------------------------------------


Pánico - ppa - N=128


------------------------------------------------------------------------------------------------------------------------------------------------------


Trastorno por estrés postraumático - ppt - N=90


------------------------------------------------------------------------------------------------------------------------------------------------------


Ansiedad por separación - psa - N=76
Tolerancia de 15% => Umbral de 0.06 a 2.82

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
0,psa001,0.064185,74.903723,24.967908,0.0,0.0,0.0,0.064185,0.0,0.0,True
6,psa003,0.064185,90.949936,8.921694,0.0,0.0,0.0,0.064185,0.0,0.0,True
9,psa004,0.064185,76.636714,23.170732,0.0,0.0,0.0,0.128370,0.0,0.0,True
13,psa005,0.064185,62.708601,37.227214,0.0,0.0,0.0,0.000000,0.0,0.0,True
16,psa006,0.064185,37.227214,62.708601,0.0,0.0,0.0,0.000000,0.0,0.0,True
24,psa007,0.064185,48.780488,50.962773,0.0,0.0,0.0,0.192555,0.0,0.0,True
28,psa008,0.064185,75.288832,24.326059,0.0,0.0,0.0,0.320924,0.0,0.0,True
31,psa009,0.064185,82.605905,17.073171,0.0,0.0,0.0,0.256739,0.0,0.0,True
34,psa010,0.064185,79.460847,20.474968,0.0,0.0,0.0,0.000000,0.0,0.0,True
37,psa011,0.064185,13.414634,86.521181,0.0,0.0,0.0,0.000000,0.0,0.0,True
44,psa012,0.064185,54.172015,45.763800,0.0,0.0,0.0,0.000000,0.0,0.0,True

Tolerancia de 16% => Umbral de 0.06 a 13.48

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
3,psa002,2.824134,58.472401,38.575096,0.0,0.0,0.0,0.12837,0.0,0.0,True

Tolerancia de 18% => Umbral de 0.06 a 37.29

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
38,psa011a,13.478819,76.957638,9.563543,0.0,0.0,0.0,0.0,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Trastorno obsesivo-compulsivo - poc - N=89


------------------------------------------------------------------------------------------------------------------------------------------------------


Bulimia - pea - N=117
Tolerancia de 6% => Umbral de 0.13 a 0.19

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_77.0,pct_88.0,pct_99.0,limited
5,pea002k,0.12837,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.770218,False
7,pea003k,0.12837,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.064185,0.641849,1.219512,False
8,pea004,0.12837,70.731707,26.765083,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,False
21,pea010,0.12837,75.930680,23.748395,0.0,0.0,0.000000,0.192555,0.000000,0.000000,0.000000,True
25,pea011,0.12837,76.251605,23.427471,0.0,0.0,0.000000,0.192555,0.000000,0.000000,0.000000,True
28,pea012,0.12837,87.419769,12.387677,0.0,0.0,0.000000,0.064185,0.000000,0.000000,0.000000,True
72,pea020,0.12837,24.582798,22.079589,0.0,0.0,53.145058,0.064185,0.000000,0.000000,0.000000,True

Tolerancia de 7% => Umbral de 0.13 a 50.13

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_77.0,pct_88.0,pct_99.0,limited
3,pea001z,0.192555,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.898588,False

Tolerancia de 12% => Umbral de 50.13 a 51.67

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_77.0,pct_88.0,pct_99.0,limited
35,pea013,50.12837,43.196406,6.611040,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
39,pea014,50.12837,47.560976,2.246470,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
45,pea015,50.12837,49.293967,0.513479,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
51,pea016,50.12837,48.973042,0.834403,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
59,pea017,50.12837,47.111682,2.695764,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
65,pea018,50.12837,46.726573,3.080873,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Trastorno de eliminación - pel - N=138


------------------------------------------------------------------------------------------------------------------------------------------------------


Pica - ppi - N=43


------------------------------------------------------------------------------------------------------------------------------------------------------


Trastorno de tics - ptc - N=57


------------------------------------------------------------------------------------------------------------------------------------------------------


Tricotilomanía - ptr - N=43


------------------------------------------------------------------------------------------------------------------------------------------------------


Depresión mayor o distimia - pmd - N=222
Tolerancia de 10% => Umbral de 0.13 a 5.58

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,limited
0,pmd001,0.12837,57.060334,42.811297,0.0,0.0,0.0,0.000000,0.0,True
7,pmd002,0.12837,77.278562,22.593068,0.0,0.0,0.0,0.000000,0.0,True
11,pmd003,0.12837,51.347882,48.523748,0.0,0.0,0.0,0.000000,0.0,True
17,pmd004,0.12837,77.278562,22.528883,0.0,0.0,0.0,0.064185,0.0,True
23,pmd005,0.12837,74.454429,25.353017,0.0,0.0,0.0,0.064185,0.0,True
27,pmd006,0.12837,80.616175,19.191271,0.0,0.0,0.0,0.064185,0.0,True
31,pmd007,0.12837,71.630295,28.241335,0.0,0.0,0.0,0.000000,0.0,True
35,pmd008,0.12837,65.789474,34.082157,0.0,0.0,0.0,0.000000,0.0,True
40,pmd009,0.12837,73.234917,26.636714,0.0,0.0,0.0,0.000000,0.0,True
44,pmd010,0.12837,86.071887,13.735558,0.0,0.0,0.0,0.064185,0.0,True
49,pmd011,0.12837,76.123235,23.684211,0.0,0.0,0.0,0.064185,0.0,True
55,pmd012,0.12837,71.822850,28.048780,0.0,0.0,0.0,0.000000,0.0,True
59,pmd013,0.12837,80.551990,19.319641,0.0,0.0,0.0,0.000000,0.0,True
64,pmd014,0.12837,85.301669,14.377407,0.0,0.0,0.0,0.192555,0.0,True
68,pmd015,0.12837,75.160462,24.582798,0.0,0.0,0.0,0.128370,0.0,True
73,pmd016,0.12837,70.795892,28.947368,0.0,0.0,0.0,0.128370,0.0,True
78,pmd017,0.12837,78.177150,21.501926,0.0,0.0,0.0,0.192555,0.0,True
82,pmd018,0.12837,54.364570,45.442875,0.0,0.0,0.0,0.064185,0.0,True
87,pmd019,0.12837,67.779204,31.964056,0.0,0.0,0.0,0.128370,0.0,True
92,pmd020,0.12837,69.448010,30.295250,0.0,0.0,0.0,0.128370,0.0,True
97,pmd021,0.12837,93.003851,6.739409,0.0,0.0,0.0,0.128370,0.0,True
104,pmd022,0.12837,93.838254,5.905006,0.0,0.0,0.0,0.128370,0.0,True

Tolerancia de 11% => Umbral de 0.13 a 40.44

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,limited
162,pmd035,5.584082,77.856226,16.495507,0.0,0.0,0.0,0.064185,0.0,True
169,pmd036,6.996149,73.812580,19.191271,0.0,0.0,0.0,0.000000,0.0,True

Tolerancia de 12% => Umbral de 0.13 a 51.48

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,limited
45,pmd010a,40.436457,52.824134,6.611040,0.0,0.064185,0.0,0.064185,0.0,True
50,pmd011a,47.432606,45.057766,7.509628,0.0,0.000000,0.0,0.000000,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Manía o hipomanía - pma - N=113
Tolerancia de 12% => Umbral de 99.55 a 99.87

   question    pct_nan   pct_0.0   pct_2.0   pct_8.0  limited
0    pma001  99.550706  0.320924  0.128370  0.000000     True
11   pma002  99.550706  0.385109  0.064185  0.000000     True
19   pma003  99.550706  0.449294  0.000000  0.000000     True
25   pma004  99.550706  0.449294  0.000000  0.000000     True
31   pma005  99.550706  0.449294  0.000000  0.000000     True
36   pma006  99.550706  0.320924  0.128370  0.000000     True
41   pma007  99.550706  0.449294  0.000000  0.000000     True
46   pma008  99.550706  0.385109  0.064185  0.000000     True
53   pma009  99.550706  0.385109  0.064185  0.000000     True
59   pma010  99.550706  0.385109  0.064185  0.000000     True
64   pma011  99.550706  0.320924  0.128370  0.000000     True
69   pma012  99.550706  0.192555  0.000000  0.256739     True
74   pma013  99.550706  0.449294  0.000000  0.000000     True

Tolerancia de 16% => Umbral de 99.55 a 99.94

   question   pct_nan   pct_0.0   pct_2.0  pct_8.0  limited
1   pma001a  99.87163  0.128370  0.000000      0.0     True
37  pma006a  99.87163  0.064185  0.064185      0.0     True
38  pma006b  99.87163  0.064185  0.064185      0.0     True
65  pma011a  99.87163  0.128370  0.000000      0.0     True
66  pma011b  99.87163  0.128370  0.000000      0.0     True

Tolerancia de 26% => Umbral de 99.94 a 100.00

   question    pct_nan   pct_0.0   pct_2.0  pct_8.0  limited
12  pma002a  99.935815  0.064185  0.000000      0.0     True
40  pma006d  99.935815  0.064185  0.000000      0.0     True
47  pma008a  99.935815  0.064185  0.000000      0.0     True
48  pma008b  99.935815  0.000000  0.064185      0.0     True
49  pma008c  99.935815  0.000000  0.064185      0.0     True
50  pma008d  99.935815  0.000000  0.064185      0.0     True
52  pma008f  99.935815  0.064185  0.000000      0.0     True
54  pma009a  99.935815  0.064185  0.000000      0.0     True
55  pma009b  99.935815  0.064185  0.000000      0.0     True
60  pma010a  99.935815  0.064185  0.000000      0.0     True
61  pma010b  99.935815  0.064185  0.000000      0.0     True

------------------------------------------------------------------------------------------------------------------------------------------------------


Esquizofrenia - psz - N=311
Tolerancia de 5% => Umbral de 0.13 a 56.61

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,limited
0,psz001,0.12837,89.602054,10.077022,0.0,0.0,0.0,0.192555,0.0,True
8,psz002,0.12837,91.270860,8.472401,0.0,0.0,0.0,0.128370,0.0,True
49,psz009,0.12837,88.125802,11.617458,0.0,0.0,0.0,0.128370,0.0,True
59,psz010,0.12837,79.139923,20.603338,0.0,0.0,0.0,0.128370,0.0,True
69,psz011,0.12837,95.635430,4.107831,0.0,0.0,0.0,0.128370,0.0,True
79,psz012,0.12837,95.827985,3.915276,0.0,0.0,0.0,0.128370,0.0,True
88,psz013,0.12837,98.780488,0.962773,0.0,0.0,0.0,0.128370,0.0,True
99,psz014,0.12837,98.138639,1.604621,0.0,0.0,0.0,0.128370,0.0,True

Tolerancia de 7% => Umbral de 0.13 a 79.40

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,limited
109,psz015,56.61104,42.811297,0.577664,0.0,0.0,0.0,0.0,0.0,True
119,psz016,56.61104,41.206675,2.182285,0.0,0.0,0.0,0.0,0.0,True
130,psz017,56.61104,41.591784,1.797176,0.0,0.0,0.0,0.0,0.0,True
139,psz018,56.61104,41.206675,2.182285,0.0,0.0,0.0,0.0,0.0,True
150,psz019,56.61104,42.554557,0.834403,0.0,0.0,0.0,0.0,0.0,True
161,psz020,56.61104,35.879332,7.509628,0.0,0.0,0.0,0.0,0.0,True
171,psz021,56.61104,43.003851,0.385109,0.0,0.0,0.0,0.0,0.0,True
181,psz022,56.61104,41.206675,2.182285,0.0,0.0,0.0,0.0,0.0,True
217,psz028,56.61104,40.500642,2.888318,0.0,0.0,0.0,0.0,0.0,True
226,psz029,56.61104,38.703466,4.685494,0.0,0.0,0.0,0.0,0.0,True
234,psz030,56.61104,39.345315,4.043646,0.0,0.0,0.0,0.0,0.0,True
242,psz031,56.61104,42.618742,0.770218,0.0,0.0,0.0,0.0,0.0,True
246,psz032,56.61104,39.730424,3.658537,0.0,0.0,0.0,0.0,0.0,True

Tolerancia de 8% => Umbral de 56.61 a 91.53

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,limited
1,psz001a,89.922978,4.749679,5.327343,0.0,0.0,0.0,0.0,0.0,True
50,psz009a,88.382542,6.546855,5.070603,0.0,0.0,0.0,0.0,0.0,True
60,psz010a,79.396662,15.340180,5.263158,0.0,0.0,0.0,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Trastorno por déficit de atención e hiperactividad - pad - N=180
Tolerancia de 12% => Umbral de 0.13 a 10.27

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_77.0,pct_88.0,pct_99.0,limited
0,pad001,0.12837,60.141207,39.666239,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
5,pad002,0.12837,70.539153,29.204108,0.0,0.0,0.0,0.128370,0.0,0.0,0.0,True
15,pad004,0.12837,56.225931,43.581515,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
20,pad005,0.12837,48.587933,51.091142,0.0,0.0,0.0,0.192555,0.0,0.0,0.0,True
25,pad006,0.12837,62.644416,37.098845,0.0,0.0,0.0,0.128370,0.0,0.0,0.0,True
30,pad007,0.12837,69.640565,30.102696,0.0,0.0,0.0,0.128370,0.0,0.0,0.0,True
35,pad008,0.12837,69.768935,29.910141,0.0,0.0,0.0,0.192555,0.0,0.0,0.0,True
40,pad009,0.12837,74.646983,25.096277,0.0,0.0,0.0,0.128370,0.0,0.0,0.0,True
45,pad010,0.12837,69.897304,29.845956,0.0,0.0,0.0,0.128370,0.0,0.0,0.0,True
53,pad011,0.12837,60.077022,39.666239,0.0,0.0,0.0,0.128370,0.0,0.0,0.0,True
84,pad022,0.12837,63.735558,36.071887,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
89,pad023,0.12837,68.035944,31.771502,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
94,pad024,0.12837,66.110398,33.568678,0.0,0.0,0.0,0.192555,0.0,0.0,0.0,True
99,pad025,0.12837,78.626444,21.116816,0.0,0.0,0.0,0.128370,0.0,0.0,0.0,True
109,pad027,0.12837,64.698331,34.980745,0.0,0.0,0.0,0.192555,0.0,0.0,0.0,True
114,pad028,0.12837,74.390244,25.288832,0.0,0.0,0.0,0.192555,0.0,0.0,0.0,True
119,pad029,0.12837,58.151476,41.591784,0.0,0.0,0.0,0.128370,0.0,0.0,0.0,True
129,pad031,0.12837,66.302953,33.311938,0.0,0.0,0.0,0.256739,0.0,0.0,0.0,True
134,pad032,0.12837,74.133504,25.545571,0.0,0.0,0.0,0.192555,0.0,0.0,0.0,True
139,pad033,0.12837,80.359435,19.319641,0.0,0.0,0.0,0.192555,0.0,0.0,0.0,True
172,pad044,0.12837,95.250321,4.492940,0.0,0.0,0.0,0.128370,0.0,0.0,0.0,True

Tolerancia de 13% => Umbral de 0.13 a 19.13

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_77.0,pct_88.0,pct_99.0,limited
10,pad003,10.269576,63.157895,26.444159,0.0,0.0,0.0,0.12837,0.0,0.0,0.0,True
104,pad026,12.901155,65.275995,21.694480,0.0,0.0,0.0,0.12837,0.0,0.0,0.0,True

Tolerancia de 14% => Umbral de 0.13 a 56.42

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_77.0,pct_88.0,pct_99.0,limited
21,pad005a,48.908858,18.100128,32.991014,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,True
124,pad030,19.127086,67.522465,13.222080,0.0,0.0,0.0,0.12837,0.0,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Trastorno de conducta - pcd - N=256
Tolerancia de 9% => Umbral de 0.13 a 1.86

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_77.0,pct_88.0,pct_99.0,limited
0,pcd001,0.12837,85.109114,14.698331,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
1,pcd002,0.12837,95.635430,4.172015,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
2,pcd003,0.12837,92.747112,7.060334,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
3,pcd004,0.12837,99.229782,0.577664,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
13,pcd007,0.12837,99.550706,0.256739,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
14,pcd008,0.12837,99.550706,0.256739,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
15,pcd009,0.12837,99.550706,0.256739,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
23,pcd012,0.12837,90.115533,9.691913,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
31,pcd013,0.12837,96.790757,3.016688,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
40,pcd014,0.12837,85.494223,14.249037,0.0,0.0,0.000000,0.128370,0.0,0.0,0.0,True
41,pcd015,0.12837,90.693196,9.114249,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
59,pcd019,0.12837,98.908858,0.898588,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
67,pcd020,0.12837,93.774069,6.033376,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
75,pcd021,0.12837,92.041078,7.702182,0.0,0.0,0.000000,0.128370,0.0,0.0,0.0,True
83,pcd022,0.12837,87.034660,12.772786,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
93,pcd023,0.12837,94.223363,5.584082,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
101,pcd024,0.12837,72.143774,10.911425,0.0,0.0,16.752246,0.064185,0.0,0.0,0.0,True
110,pcd025,0.12837,91.078306,8.729140,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
128,pcd027,0.12837,84.852375,14.955071,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
139,pcd028,0.12837,96.405648,3.401797,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True
149,pcd029,0.12837,98.138639,1.732991,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,True
213,pcd039,0.12837,96.469833,3.337612,0.0,0.0,0.000000,0.064185,0.0,0.0,0.0,True

Tolerancia de 10% => Umbral de 0.13 a 1.99

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_77.0,pct_88.0,pct_99.0,limited
49,pcd018,1.861361,74.646983,23.427471,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
120,pcd026,1.925546,87.548139,10.462131,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
174,pcd029t,1.861361,96.662388,1.476252,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,True

Tolerancia de 11% => Umbral de 0.13 a 76.57

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_77.0,pct_88.0,pct_99.0,limited
194,pcd036,1.98973,94.672657,3.273427,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
203,pcd037,1.98973,85.365854,12.580231,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True
204,pcd038,1.98973,87.034660,10.911425,0.0,0.0,0.0,0.064185,0.0,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Trastorno de oposición desafiante - pod - N=101
Tolerancia de 12% => Umbral de 0.13 a 44.29

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
0,pod001,0.12837,62.195122,37.548139,0.0,0.0,0.0,0.128370,0.0,0.0,True
5,pod002,0.12837,43.966624,55.712452,0.0,0.0,0.0,0.192555,0.0,0.0,True
10,pod003,0.12837,70.410783,29.332478,0.0,0.0,0.0,0.128370,0.0,0.0,True
15,pod004,0.12837,60.012837,39.730424,0.0,0.0,0.0,0.128370,0.0,0.0,True
20,pod005,0.12837,75.930680,23.812580,0.0,0.0,0.0,0.128370,0.0,0.0,True
27,pod006,0.12837,74.454429,25.288832,0.0,0.0,0.0,0.128370,0.0,0.0,True
34,pod007,0.12837,57.766367,42.105263,0.0,0.0,0.0,0.000000,0.0,0.0,True
39,pod008,0.12837,57.702182,42.105263,0.0,0.0,0.0,0.064185,0.0,0.0,True
46,pod009,0.12837,45.571245,54.107831,0.0,0.0,0.0,0.192555,0.0,0.0,True
53,pod010,0.12837,91.142490,8.600770,0.0,0.0,0.0,0.128370,0.0,0.0,True
61,pod011,0.12837,90.821566,8.921694,0.0,0.0,0.0,0.128370,0.0,0.0,True
69,pod012,0.12837,81.771502,17.907574,0.0,0.0,0.0,0.192555,0.0,0.0,True

Tolerancia de 13% => Umbral de 0.13 a 52.63

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
6,pod002a,44.287548,25.545571,30.166881,0.0,0.0,0.0,0.0,0.0,0.0,True

Tolerancia de 14% => Umbral de 0.13 a 57.89

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
49,pod009c,52.631579,23.748395,23.620026,0.0,0.0,0.0,0.0,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Abuso de alcohol - pal - N=110
Tolerancia de 5% => Umbral de 0.13 a 88.19

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
0,pal001,0.128370,75.288832,24.518614,0.0,0.0,0.000000,0.064185,0.000000,0.0,True
1,pal001ay,75.481386,0.000000,0.064185,0.0,0.0,0.320924,0.256739,0.064185,0.0,False
3,pal001b,79.011553,4.236200,16.752246,0.0,0.0,0.000000,0.000000,0.000000,0.0,True
4,pal001c,79.717587,8.472401,11.810013,0.0,0.0,0.000000,0.000000,0.000000,0.0,True
5,pal001d,87.291399,9.948652,2.759949,0.0,0.0,0.000000,0.000000,0.000000,0.0,True

Tolerancia de 13% => Umbral de 88.19 a 88.32

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
7,pal001f,88.189987,0.000000,2.952503,1.668806,0.000000,0.000000,0.000000,0.0,0.000000,False
8,pal001g,88.189987,2.631579,9.178434,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,True
10,pal001i,88.189987,0.000000,2.118100,0.962773,0.320924,0.320924,0.128370,0.0,0.000000,False
11,pal001j,88.189987,8.793325,0.641849,0.256739,0.192555,0.064185,0.000000,0.0,0.064185,False
12,pal001k,88.189987,7.381258,4.428755,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,True
13,pal001ly,88.189987,2.374840,0.000000,0.000000,0.000000,0.000000,0.064185,0.0,0.064185,False
23,pal006,88.189987,10.462131,1.347882,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,True
30,pal009,88.189987,10.654685,1.155327,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,True
32,pal010,88.189987,10.975610,0.834403,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,True

Tolerancia de 14% => Umbral de 88.19 a 88.96

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_88.0,pct_99.0,limited
15,pal002,88.318357,10.526316,1.091142,0.0,0.0,0.064185,0.0,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Consumo de marihuana - pmj - N=87
Tolerancia de 5% => Umbral de 0.13 a 96.02

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_8.0,pct_9.0,limited
0,pmj001,0.128370,93.453145,6.354300,0.0,0.0,0.064185,True
1,pmj001ay,93.645700,0.000000,0.000000,0.0,0.0,0.064185,False
3,pmj001b,94.544288,2.118100,3.337612,0.0,0.0,0.000000,True
4,pmj001c,95.763800,1.861361,2.374840,0.0,0.0,0.000000,True

Tolerancia de 6% => Umbral de 0.13 a 97.63

  question    pct_nan   pct_0.0   pct_2.0  pct_3.0  pct_8.0  pct_9.0  limited
5  pmj001d  96.020539  3.016688  0.962773      0.0      0.0      0.0     True

Tolerancia de 22% => Umbral de 97.63 a 97.69

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_8.0,pct_9.0,limited
7,pmj001f,97.62516,0.000000,0.770218,0.256739,0.0,0.000000,False
8,pmj001g,97.62516,1.091142,1.283697,0.000000,0.0,0.000000,True
18,pmj006,97.62516,2.118100,0.256739,0.000000,0.0,0.000000,True
24,pmj009,97.62516,2.182285,0.192555,0.000000,0.0,0.000000,True
26,pmj010,97.62516,1.668806,0.706033,0.000000,0.0,0.000000,True
28,pmj011,97.62516,1.668806,0.706033,0.000000,0.0,0.000000,True
31,pmj012,97.62516,1.925546,0.449294,0.000000,0.0,0.000000,True
33,pmj013,97.62516,1.925546,0.449294,0.000000,0.0,0.000000,True
35,pmj014,97.62516,2.053915,0.320924,0.000000,0.0,0.000000,True
37,pmj015,97.62516,1.925546,0.385109,0.000000,0.0,0.064185,True
38,pmj016,97.62516,2.182285,0.192555,0.000000,0.0,0.000000,True
40,pmj017,97.62516,2.374840,0.000000,0.000000,0.0,0.000000,True
42,pmj018,97.62516,2.310655,0.064185,0.000000,0.0,0.000000,True
43,pmj019,97.62516,2.310655,0.064185,0.000000,0.0,0.000000,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Consumo de otras sustancias - psu - N=240
Tolerancia de 5% => Umbral de 0.13 a 99.23

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,limited
0,psu001,0.12837,99.614891,0.192555,0.0,0.000000,0.0,0.064185,True
11,psu002,0.12837,99.550706,0.192555,0.0,0.064185,0.0,0.064185,True
22,psu003,0.12837,99.037227,0.770218,0.0,0.000000,0.0,0.064185,True
33,psu004,0.12837,99.807445,0.000000,0.0,0.000000,0.0,0.064185,True
43,psu005,0.12837,99.807445,0.000000,0.0,0.000000,0.0,0.064185,True
54,psu006,0.12837,99.807445,0.000000,0.0,0.000000,0.0,0.064185,True
64,psu007,0.12837,99.743261,0.064185,0.0,0.000000,0.0,0.064185,True
75,psu008,0.12837,99.807445,0.000000,0.0,0.000000,0.0,0.064185,True
86,psu009,0.12837,99.679076,0.128370,0.0,0.000000,0.0,0.064185,True
97,psu010,0.12837,99.743261,0.064185,0.0,0.000000,0.0,0.064185,True
107,psu011,0.12837,99.486521,0.320924,0.0,0.000000,0.0,0.064185,True

Tolerancia de 6% => Umbral de 0.13 a 99.49

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,limited
23,psu003a,99.229782,0.770218,0.0,0.0,0.0,0.0,0.0,True
24,psu003by,99.229782,0.000000,0.0,0.0,0.0,0.0,0.0,False

Tolerancia de 7% => Umbral de 0.13 a 99.55

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,limited
26,psu003c,99.486521,0.320924,0.192555,0.0,0.0,0.0,0.0,True
28,psu003e,99.486521,0.513479,0.000000,0.0,0.0,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------


Consumo de tabaco - pni - N=85
Tolerancia de 5% => Umbral de 0.13 a 83.89

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_99.0,limited
0,pni001,0.128370,79.589217,20.089859,0.000000,0.000000,0.000000,0.192555,0.0,True
1,pni001ay,79.910141,0.000000,0.000000,0.064185,0.256739,0.256739,0.513479,0.0,False
3,pni001b,82.092426,5.584082,12.323492,0.000000,0.000000,0.000000,0.000000,0.0,True
6,pni002,0.128370,95.186136,0.064185,0.000000,0.192555,0.000000,4.428755,0.0,True

Tolerancia de 6% => Umbral de 0.13 a 85.49

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_99.0,limited
67,pni028,83.889602,11.232349,4.878049,0.0,0.0,0.0,0.0,0.0,True

Tolerancia de 9% => Umbral de 82.09 a 90.50

,question,pct_nan,pct_0.0,pct_2.0,pct_3.0,pct_7.0,pct_8.0,pct_9.0,pct_99.0,limited
4,pni001c,85.494223,4.813864,9.691913,0.0,0.0,0.0,0.0,0.0,True
12,pni003,85.494223,5.006418,9.499358,0.0,0.0,0.0,0.0,0.0,True

------------------------------------------------------------------------------------------------------------------------------------------------------